edouarda/brigand

brigand/back.hpp
brigand/detail/last_element.hpp

- Unroll last_element from  1 to 8 types
- move implementation to detail/ folder

Add fast-lane implementation to speedup back implementation

---

brigand/functions/xor.hpp

(A xor B) == ((!A && B) || (A && !B) == (A != B)
The last one is much cheaper because it's just one operation compared to five of the trivial solution.

XOR is the same as !=

---

.travis.yml

Make travis use container based test so we can start tests faster and use new compiler packages easily. N Tests Matrix includes 2 flavors of clang and 3 flavor of g++

More test in Travis matrix

---

.clang-format

Fixes issue #97.
It's hard to write a config file that will correspond to the existing codebase, because its formatting is not consistent.
VS extension available here: http://llvm.org/builds/

Add .clang-format config file.

---

.clang-format
brigand/algorithms/remove.hpp
standalone/brigand.hpp
test/remove_test.cpp

This fixes issue #100.
Fix clang-format to always break line after `template <...>`.
Update standalone.

Rename `remove` -> `remove_if` and `remove_element` -> `remove`.

---

CMakeLists.txt
brigand/adapted/list.hpp
brigand/sequences/keys_as_sequence.hpp
brigand/sequences/values_as_sequence.hpp
standalone/brigand.hpp
test/for_each.cpp
test/keys_as_sequence.cpp
test/map_test.cpp
test/map_test.hpp
test/values_as_sequence.cpp

Add `map_keys_list<Map, Sequence = set>`, `map_values_list<Map, Sequence = list>` that returns a Sequence of keys/values of a map.
These are convience functions.
I've added as well `as_sequence<L, Sequence>` that is a generalisation of `as_list<L> = as_sequence<L, list>`.
Names to be discussed.

Add keys_as_sequence and values_as_sequence

---

CMakeLists.txt
brigand/algorithms/index_of.hpp
test/index_of.cpp

The result is `no_such_type_` if the type is not present in the sequence.
Fixes issue #121.

Implement `index_of` and `index_if`.

---

brigand/sequences/back.hpp
brigand/sequences/front.hpp
test/list_test.cpp

As requested on #133.
(The current version returns an empty list if the number of items exceeds that of the list)

Compilation error if the number of elements to be removed exceeds that of the list

---

brigand/algorithms/is_set.hpp

`//list<int, int, int, ...>`
`using list = brigand::wrap<brigand::filled_list<int, N_L1>, brigand::is_set>;`
Before:
clang | 00.07s - 37M | 00.11s - 40M | 00.22s - 46M | 00.56s - 66M | ko
gcc | 00.06s - 21M | 00.12s - 31M | 00.29s - 52M | 01.09s - 122M | 05.95s - 373M
After:
clang | 00.05s - 36M | 00.06s - 36M | 00.06s - 37M | 00.07s - 38M | 00.08s - 39M
gcc | 00.04s - 19M | 00.04s - 19M | 00.05s - 21M | 00.07s - 23M | 00.12s - 28M
----
`//list<_1, _2, _3, ...>`
`using list = brigand::wrap<brigand::range<int, 0, N_L1>, brigand::is_set>;`
Before:
clang | 00.07s - 37M | 00.14s - 40M | …

optimized brigand::is_set

---

brigand/algorithms/detail/fold.hpp

Tips: Types members impacts the performance of gcc.
----
```cpp
using list = brigand::fold<
brigand::range<int, 0, N_L1>,
std::integral_constant<int, 0>,
brigand::plus<brigand::_state, brigand::_element>
>;
```
Before:
clang | 00.07s - 37M | 00.10s - 39M | 00.15s - 42M | 00.24s - 49M | 00.44s - 63M
gcc | 00.05s - 21M | 00.10s - 27M | 00.16s - 35M | 00.28s - 53M | 00.55s - 93M
After:
clang | 00.07s - 36M | 00.10s - 39M | 00.15s - 42M | 00.24s - 49M | 00.44s - 63M
gcc | 00.05s - 21M | 00.10s - 27M | 00.15s - 34M | 00.26s - 50M | 00.50s - 84M

optimized brifand::fold on gcc

---

brigand/algorithms/flatten.hpp

```cpp
using list = brigand::flatten<brigand::filled_list<int, SIZE>>;
```
Before:
clang | 00.05s - 35M | 00.05s - 36M | 00.07s - 39M | 00.12s - 49M | ko
gcc | 00.04s - 19M | 00.04s - 21M | 00.06s - 25M | 00.12s - 40M | 00.30s - 92M
After:
clang | 00.05s - 35M | 00.05s - 35M | 00.05s - 36M | 00.06s - 37M | 00.09s - 41M
gcc | 00.03s - 18M | 00.04s - 18M | 00.04s - 19M | 00.04s - 20M | 00.06s - 24M
---
```cpp
// list<list<list<...>, int>, int>
using list = brigand::flatten<
brigand::fold<
brigand::filled_list<int, SIZE>,
brigand::list<>,
brigand::list<brigand::_state, brigand::_element>
>
>;
```
Before:
--- | --- | --- | …

optimized brigand::flatten

---

CMakeLists.txt
brigand/sequences/erase.hpp
test/erase_c_test.cpp

Little extra cost for a small list or a small index.
---
```cpp
using list = brigand::erase_c<brigand::range<int, 0, SIZE>, 0>;
```
Before:
clang | 00.05s - 35M | 00.06s - 36M | 00.06s - 36M | 00.07s - 36M | 00.07s - 37M
gcc | 00.04s - 19M | 00.04s - 19M | 00.05s - 19M | 00.05s - 20M | 00.06s - 21M
After:
clang | 00.06s - 36M | 00.07s - 36M | 00.07s - 37M | 00.07s - 37M | 00.08s - 38M
gcc | 00.05s - 20M | 00.05s - 20M | 00.05s - 20M | 00.06s - 21M | 00.07s - 22M
---
```cpp
using list = brigand::erase_c<brigand::range<int, 0, SIZE>, SIZE/2>;
```
Before:
clang | 00.05s - 35M | 00.06s - 36M …

Optimized erase_c with a big index

---

brigand/algorithms/remove.hpp

```cpp
using list = brigand::remove<brigand::range<int, 0, SIZE>, std::integral_constant<int, SIZE/2>>;
```
Before:
clang | 00.06s - 36M | 00.09s - 38M | 00.12s - 41M | 00.20s - 46M | 00.33s - 58M
gcc | 00.05s - 21M | 00.09s - 26M | 00.13s - 33M | 00.22s - 46M | 00.40s - 73M
After:
clang | 00.06s - 36M | 00.07s - 36M | 00.07s - 37M | 00.09s - 38M | 00.12s - 42M
gcc | 00.04s - 20M | 00.05s - 20M | 00.06s - 21M | 00.07s - 23M | 00.11s - 28M
---
```cpp
using list = brigand::remove_if<brigand::range<int, 0, SIZE>, is_odd<brigand::_1>>;
```
Before:
clang | 00.07s - 36M | 00.09s - 38M | 00.13s …

Optimized brigand::remove and brigand::remove_if

---

brigand/sequences/make_sequence.hpp

```cpp
using list = brigand::make_sequence<std::integral_constant<int,0>, SIZE>;
```
Before:
clang | 00.07s - 35M | 00.08s - 36M | 00.09s - 37M | 00.12s - 39M | 00.18s - 43M
gcc | 00.05s - 20M | 00.07s - 23M | 00.10s - 27M | 00.15s - 35M | 00.27s - 55M
After:
clang | 00.06s - 35M | 00.07s - 36M | 00.09s - 37M | 00.12s - 39M | 00.18s - 43M
gcc | 00.05s - 20M | 00.06s - 22M | 00.09s - 26M | 00.13s - 32M | 00.22s - 46M

optimized make_sequence with gcc

---

brigand/sequences/map.hpp
test/map_test.cpp

```cpp
template<int N, class L = brigand::range<int, 0, N>>
struct mk_map;
template<int N, class... T>
struct mk_map<N, brigand::list<T...>> {
using type = brigand::map<brigand::pair<T,T>...>;
};
using list = brigand::at<mk_map<SIZE>::type, std::integral_constant<int, INDEX>>;
```
With INDEX = `0`, `SIZE/4`, `SIZE/2`, `SIZE-1` and `SIZE` (no differences).
Before:
clang | 00.06s - 34M | 00.06s - 35M | 00.07s - 36M | 00.09s - 39M | 00.14s - 46M
gcc | 00.04s - 19M | 00.05s - 21M | 00.06s - 23M | 00.09s - 28M | 00.16s - 43M
After:
clang | 00.06s - 34M | 00.06s - 35M | 00.06s - 35M | 00.07s - 36M | 00.08s - 38M
gcc | 00.04s - 19M | 00.05s - 20M | 00.05s - 21M …

optimized map::at

---

brigand/sequences/at.hpp

before change, trying to get at<N, List<Ts...>> where Ts... contained one or more reference types would cause a pointer-to-reference error

allow reference types in at<...> implementation

---

script/briganddoc.py

@jfalcou here you are! You can see what it generates right [here](https://github.com/ccharly/brigand/wiki/Reference) (as_list was actually manually created, this is why it is empty).
The script will generate a `.md` for every `.hpp` (you can blacklist some of them, see `blacklist` variable inside the script). The `Reference.md` is automatically updated and you can also update it manually, the script will automatically merge existing entries and new ones.
You can create manually your own `.md`, but make sure to follow the same scheme. For example, if you want to create the documentation for `as_list`, you can create the file: `adapted.as_list.md` and add it to the reference manually.
Files already generated won't be regenerated by the script.
Just let me know if you have other questions. …

Add briganddoc.py

---

brigand/sequences/range.hpp

```cpp
using list1 = brigand::range<int, 0, SIZE>;
using list2 = brigand::range<long, 0, SIZE>;
using list3 = brigand::range<long long, 0, SIZE>;
using list4 = brigand::range<unsigned long long, 0, SIZE>;
```
Gcc:
Size = |      10      |      50      |     100      |     200      |     400
------ | ------------ | ------------ | ------------ | ------------ | ------------
before | 00.04s - 16M | 00.05s - 17M | 00.05s - 18M | 00.07s - 20M | 00.11s - 24M
after  | 00.03s - 16M | 00.04s - 17M | 00.04s - 17M | 00.05s - 18M | 00.06s - 19M
gain ~ |   25%  - 0% |   20% - 3% |   20% - 6% |   28% - 11% |   45% - 20%
Clang:
Size = |      10      |      50      |     100      |     200      |     400
------ | ------------ | ------------ | ------------ | ------------ | ------------
before | 00.06s - 36M …

Optimized range

---

brigand/sequences/map.hpp

```cpp
template<int N, class L = brigand::range<int, 0, N>>
struct mk_map;
template<int N, class... T>
struct mk_map<N, brigand::list<T...>> {
using type = brigand::map<brigand::pair<T,T>...>;
};
template<class T> using fn = decltype(mk_map<SIZE>::type::insert(brigand::type_<brigand::pair<T,int>>{}));
using list = brigand::transform<mk_map<SIZE>::type, brigand::quote<fn>>;
```
Gcc:
Size = |      100      |      200      |      300
------ | ------------- | ------------- | -------------
before | 00.19s -  49M | 00.51s - 115M | 00.98s - 266M
after  | 00.12s -  38M | 00.28s -  78M | 00.53s - 167M
Clang:
Size = |      100      |      200      |      300
------ | ------------- | ------------- | -------------
before | 00.18s -  48M | 00.43s -  75M | 00.76s - 116M
after  | 00.12s -  41M | 00.22s …

Optimized map::insert

---

CMakeLists.txt

The source directory for the header-install command needs point to brigand. Otherwise the headers will be installed into $CMAKE_INSTALL_PREFIX/include/include/brigand.

Fix header install path

---

include/brigand/functions/arithmetic/divides.hpp
include/brigand/functions/arithmetic/max.hpp
include/brigand/functions/arithmetic/min.hpp
include/brigand/functions/arithmetic/minus.hpp
include/brigand/functions/arithmetic/modulo.hpp
include/brigand/functions/arithmetic/plus.hpp
include/brigand/functions/arithmetic/times.hpp
test/integral_test.cpp

Adding an int and a long will deduce to a long instead of an int.

Integer math operations deduce types

---

include/brigand/functions/logical/and.hpp
include/brigand/functions/logical/or.hpp
test/logical_test.cpp

I've added a variadic overload for the `and_` and `or_` logical operators, which should scale linearly with the size of the parameter pack.
The general idea is quite simple:
1. Declare a variadic class template.
2. Specialize for the 0-case (true for `and_` and false for `or_`).
3. Use recursion to implement the operator (for `and_`, using `T::value && and_<Ts...>::value`.).
I've implemented test cases for the 0-arg, 1-arg, and 3-arg cases, demonstrating that they are logically sound. Since the implementation is recursive, demonstrating the 0 and 1-arg cases would prove the N-arg case.

Added variadic and_/or_ and tests for 0-arg, 1-arg, and 3-arg cases

---

CMakeLists.txt
doc/Doxyfile.in
examples/CMakeLists.txt
examples/flatten.cpp
include/brigand/algorithms/flatten.hpp

I will add a configuration to travis to build and push the documentation to gh-pages in a separate PR. For now, I want to start getting documentation in so users can look at it.

Add documentation for brigand::flatten

---

.travis.yml
doc/Doxyfile.in

- This currently uses Doxygen, the main reason being I'm most familiar with it and want to get content up quickly. Once things are working I'll look at switching to standardese.
- I have a copy of the current documentation on my fork's gh-pages branch: http://nilsdeppe.com/brigand/

Build documentation on travis-ci and push to gh-pages

---

include/brigand/algorithms/replace.hpp
include/standalone/brigand.hpp
test/replace.cpp

The metalambda in the implementation needed to be hidden from the
outer parser.

Fix lazy::replace when used in a metalambda

---

include/brigand/sequences/map.hpp
include/standalone/brigand.hpp
test/map_test.cpp

Previously the values were improperly used in the uniqueness check.

Prevent insertion of duplicate keys in maps

---

CMakeLists.txt
test/CMakeLists.txt

Move CMake code that sets up tests to `test/`. Also add `BUILD_EXAMPLES` option.
Now a configuration like this:
```
cmake -D BUILD_TESTING=OFF ..
```
doesn't compile anything on `make all`, as expected for a header-only library. This simplifies installation with [Spack](https://github.com/spack/spack).
See the [CMake docs on Test](https://cmake.org/cmake/help/latest/module/CTest.html) for the standard way to set up tests.

Add standard CMake `BUILD_TESTING` option

---

include/brigand/algorithms/all.hpp
include/brigand/algorithms/count.hpp
include/brigand/algorithms/none.hpp
include/standalone/brigand.hpp

Just falls back to the existing backup implementation.  I couldn't come up with a way to modify the main implementation to work.
Also fixes a minor bug in count noticed during testing in #274.
@nilsleiffischer Can you verify that this fixes your troubles?

Fix all/none on C++11 libc++
