CMakeLists.txt, README.md, brigand/arithmetic.hpp, brigand/complement.hpp, brigand/divides.hpp, brigand/modulo.hpp, brigand/negate.hpp, brigand/next.hpp, brigand/not.hpp, brigand/prev.hpp, brigand/times.hpp, test/integral_test.cpp
Added :  * / % ++ -- unary - and ~
Fixed : not to not_ as not is a reserved keyword on g++/clang
=> More MPL arithmetic

CMakeLists.txt, brigand/and.hpp, brigand/bool.hpp, brigand/logical.hpp, brigand/or.hpp, brigand/xor.hpp, test/integral_test.cpp, test/logical_test.cpp
Added logical operators on meta-boolean
Added meta-boolean
=> Implement logical operator

brigand/sequences/map.hpp
=> Duplicate in map

brigand/adapted/pair.hpp, brigand/adapted/tuple.hpp
By @Jarod42, see https://github.com/edouarda/brigand/commit/ba47f55618bf2e147e1e1837773ed182cd65cdec
=> It is undefined behavior to forward declare in std

CMakeLists.txt, brigand/algorithms.hpp, brigand/algorithms/select.hpp, test/mpl_test.cpp, test/select.cpp
Implement a statically resolved runtime selector, akin to static_if
=> select - static conditional runtime selector

CMakeLists.txt, brigand/adapted.hpp, brigand/adapted/fusion.hpp, test/fusion_test.cpp
This may requires appveyor to use Boost install for proper testting.
=> Support adaptation to boost::fusion

brigand/sequences/at.hpp
After discussions with @ldionne and @pfultz2 we redesigned at to use a trick allwoign use to "jump" over N argumetn sin an argument pack. THis also use range, which mean at_c is now fast-laned.
=> Reworked at_c implementation

CMakeLists.txt, brigand/adapted.hpp, brigand/adapted/variant.hpp, brigand/brigand.hpp, script/embed.py, standalone/brigand.hpp, test/include_test.cpp
To ease integration of Brigand as a third party component, we provide a rule colalpsing every headers into a single file.
Compression script courtesy of NumScale
=> Standalone header generator

CMakeLists.txt, brigand/algorithms.hpp, brigand/algorithms/partition.hpp, brigand/algorithms/sort.hpp, brigand/functions/lambda/protect.hpp, test/partition_test.cpp, test/protect.cpp, test/sort_test.cpp
`patition`, `sort` and fix `has_placeholders` with `protect`.
=> Partition and sort (v3 :D)

brigand/algorithms/partition.hpp, test/partition_test.cpp
Nothing crucial, just the test had inversed odd and even.
=> Fix partition test.

CMakeLists.txt, brigand/algorithms.hpp, brigand/algorithms/detail/replace.hpp, brigand/algorithms/replace.hpp, test/replace.cpp
replace: replaces all occurrences of a given type in the sequence by a new type.
replace_if: replaces all types fullfiling a given predicate in the sequence by a new type.
=> Add replace and replace_if algorithms

CMakeLists.txt, script/embed.py, standalone/brigand.hpp
See changes in the commit list.
No code changes, only scripts/CMake.
=> Fix standalone

script/pre-commit
This fixes issue #105.
We might as well modify the commit message, but I don't deem it necessary.
=> Invoke standalone from the pre-commit hook.

brigand/functions/lambda/quote.hpp
Less parameters to quote_impl (List and MetaFunction removed)
=> optimized quote

brigand/sequences/at.hpp, brigand/sequences/filled_list.hpp, brigand/sequences/make_sequence.hpp, brigand/sequences/range.hpp, test/make_sequence_test.cpp
=> make_sequence takes a lambda for next

brigand/sequences/filled_list.hpp
And also more efficient with big list (several thousands of elements).
=> pretty filled_list :)

brigand/sequences/back.hpp, brigand/sequences/front.hpp, test/list_test.cpp
=> pop_front_n / pop_back_n

brigand/algorithms/reverse.hpp
Before:
clang | 00.05s - 36M | 00.07s - 37M | 00.08s - 40M | 00.15s - 49M | ko
gcc | 00.04s - 19M | 00.05s - 21M | 00.07s - 25M | 00.13s - 38M | 00.32s - 80M
After:
clang | 00.05s - 36M | 00.06s - 36M | 00.06s - 36M | 00.06s - 37M | 00.09s - 40M
gcc | 00.04s - 18M | 00.04s - 19M | 00.05s - 19M | 00.05s - 20M | 00.07s - 23M
=> optimized brigand::reverse

brigand/algorithms/partition.hpp
```cpp
template <typename N>
using is_odd = std::integral_constant<bool, (N::value % 2)>;
using list = brigand::partition<brigand::range<int, 0, SIZE>, brigand::quote<is_odd>>;
```
Before:
clang | 00.07s - 36M | 00.09s - 38M | 00.12s - 41M | 00.20s - 48M | 00.41s - 72M
gcc | 00.05s - 21M | 00.08s - 26M | 00.13s - 33M | 00.23s - 51M | 00.49s - 98M
After:
clang | 00.06s - 36M | 00.09s - 38M | 00.12s - 40M | 00.19s - 45M | 00.34s - 57M
gcc | 00.05s - 21M | 00.08s - 26M | 00.12s - 32M | 00.20s - 45M | 00.38s - 71M
=> optimized brigand::partition

brigand/algorithms/detail/replace.hpp, brigand/algorithms/replace.hpp, test/replace.cpp
```cpp
using list = brigand::replace<brigand::range<int, 0, SIZE>, int, int>;
```
Before:
clang | 00.07s - 36M | 00.11s - 39M | 00.16s - 42M | 00.26s - 49M | 00.48s - 62M
gcc | 00.06s - 21M | 00.11s - 29M | 00.18s - 40M | 00.32s - 61M | 00.60s - 103M
After:
clang | 00.06s - 36M | 00.09s - 38M | 00.12s - 40M | 00.19s - 45M | 00.32s - 54M
gcc | 00.05s - 20M | 00.08s - 25M | 00.13s - 31M | 00.22s - 43M | 00.40s - 67M
---
```cpp
template<class N> struct is_odd { using type = std::integral_constant<bool, (N::value % 2)>; };
using list = brigand::replace<brigand::range<int, 0, SIZE>, is_odd<brigand::_1>, int>;
```
Before:
--- | …
=> optimized brigand::replace and brigand::replace_if

brigand/sequences/set.hpp
```cpp
template<int N, int I>
using mk_list = brigand::erase<
brigand::wrap<brigand::range<int, 0, N>, brigand::set>,
std::integral_constant<int, I>
>;
```
---
```cpp
using list = mk_list<SIZE, 0>;
```
Before:
clang | 00.06s - 36M | 00.08s - 37M | 00.09s - 39M | 00.14s - 45M | 00.28s - 66M
gcc | 00.05s - 21M | 00.06s - 23M | 00.08s - 26M | 00.13s - 34M | 00.28s - 61M
After:
clang | 00.07s - 36M | 00.08s - 37M | 00.09s - 39M | 00.13s - 43M | 00.20s - 51M
gcc | 00.05s - 21M | 00.07s - 22M | 00.08s - 25M | 00.13s - 30M | 00.21s - 41M
---
```cpp
using list = mk_list<SIZE, SIZE/4>;
```
Before: …
=> Optimized set::erase

brigand/sequences/at.hpp, test/list_test.cpp
=> fixes at_c with C-style array

brigand/sequences/map.hpp, test/map_test.cpp
=> map::erase and map::has_key

brigand/algorithms/all.hpp, brigand/algorithms/none.hpp
roughly 30% speed increase on clang 3.7 and 50% on MSVC15
=> All and none speed increase

brigand/types/operators.hpp
Add xor bitwise operator to go with other bitwise operators.
=> add xor operator for std::integral_constant

brigand/algorithms/split.hpp, brigand/algorithms/split_at.hpp
=> Fix compile with Intel compiler

include/brigand/version.hpp
=> Add version macros

include/brigand/functions/logical/and.hpp, include/brigand/functions/logical/or.hpp
=> Bug fix for C4800 warning on MSVC.

include/brigand/algorithms/count.hpp
These changes are because of what appears to be a bug in clang when c++1z is used. However, since the subscript operator of array is not constexpr in C++11 we must special case for C++14 and newer.
=> Add support for C++1z with clang

.github/workflows/Tests.yaml
Compile and test on [ubuntu-latest, macos-latest] x [gcc, clang]. See https://github.com/nilsleiffischer/brigand/actions/runs/1701814008 for an example run. It exhibits the issue #274.
=> Add basic CI tests
